name: CI - build and test

on:                                
  push:
    branches: [ master ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build
      working-directory: ./GitLab2
      run: ../gradlew build
    - name: Test
      working-directory: ./GitLab2
      run: ../gradlew test
